In [18]:
import pandas as pd

df = pd.read_csv('https://stepik.org/media/attachments/lesson/681964/2_2_8.csv')
ans = pd.read_csv('https://stepik.org/media/attachments/lesson/681964/2_2_8_ans.csv', index_col=0)

df['tripple_accident'] = df['user_time_accident'] * 3
df['rides_on_rating'] = df['user_rides'] / df['user_rating']
df = df.loc[df['user_time_accident'] > 25]
df.loc[df['age'] > df['age'].mean()]

,user_id,user_rating,age,user_rides,user_time_accident,tripple_accident,rides_on_rating
3,E10711310m,8.4,33,322,39.0,117.0,38.333333
64,t25217963K,8.0,30,101,72.0,216.0,12.625000

In [15]:
import pandas as pd

df = pd.read_csv('../data/driver_info.csv')
df.loc[((df['user_time_accident'] > 4.5) & (df['user_time_accident'] <= 9.0)) & (df['age'] < 40)].count()

age                   2478
user_rating           2478
user_rides            2478
user_time_accident    2478
user_id               2478
sex                   2478
first_ride_date       2478
dtype: int64

In [16]:
import pandas as pd

df1 = pd.read_csv('https://stepik.org/media/attachments/lesson/681964/2.2.6_df1.csv', index_col=0)
df2 = pd.read_csv('https://stepik.org/media/attachments/lesson/681964/2.2.6_df2.csv', index_col=0)

user_white_list = ['g10995906g', 'H90312511Q', 'C27138482L', 'H22518078t', 'n17438464n', 'F10525768e', 's15596151o', 'i18954748S', 'E84048392U', 'E69893354s']
car_black_list = ['l-4285389z', 'n79502261g', 'N-1839822D']

df = pd.concat([df1, df2])
white_mask = df['user_id'].isin(user_white_list)
black_mask = df['car_id'].isin(car_black_list)
df = df.loc[(df['rating'] > 4) & (df['stop_times'].isin([2, 3, 5]))].loc[(white_mask) & (~black_mask)]
result = df.loc[df.index % 2 == 0]
pd.read_csv('https://stepik.org/media/attachments/lesson/681964/2_2_6_ans.csv', index_col=0)

        user_id      car_id  rating  stop_times
20   C27138482L  M-1786506l    7.42           2
190  F10525768e  I98930031r    4.21           2
248  s15596151o  u-2070489i    5.39           2

In [17]:
import pandas as pd

df = pd.read_csv('../data/driver_info.csv')
df.head()
df['age'].median().round(0)
df['age'].describe().round(1)
df['user_rating'].describe().round(1)
df['user_time_accident'].value_counts()

user_time_accident
6.0     843
3.0     794
8.0     777
4.0     760
11.0    752
       ...
82.0      1
85.0      1
84.0      1
80.0      1
83.0      1
Name: count, Length: 84, dtype: int64

In [103]:
import pandas as pd

df = pd.read_csv('https://stepik.org/media/attachments/lesson/681964/2_2_10.csv')

# Учтите, что new_index, new_data, del_index_list, index в тестовой системе будут иметь другие значения
new_index = 50
new_data = ['new_car_id', 'new_worker_id', '2019-11-11 4:44','refuel_check', 3.5, 10]
del_index_list = [41, 18, 33, 7, 46]
index = 22


# В ans содержится правильный ответ. Перед отправкой своего решения, сравнитесь с ним.
ans = pd.read_csv('https://stepik.org/media/attachments/lesson/681964/2_2_10_ans.csv')

df.loc[new_index] = new_data
df.drop(index=del_index_list, inplace=True)
df.loc[index, ['destroy_degree']] += 1
df.drop('fix_date', axis=1, inplace=True)
df['efficient'] = df['destroy_degree'] / df['work_duration']
df['work_duration'] **= 2
df.rename({'work_duration': 'work_duration_square'}, axis=1, inplace=True)
df.drop_duplicates(subset='car_id', inplace=True)
df

,car_id,worker_id,work_type,destroy_degree,work_duration_square,efficient
0,C-8860661H,BM,reparking,1.0,784,0.035714
1,Z76775340d,IL,repair,8.4,2304,0.175000
2,r12485993Y,HN,reparking,1.0,441,0.047619
3,Z-1382353b,VX,repair,5.7,169,0.438462
4,p14707024B,JP,refuel_check,1.0,441,0.047619
5,f-1883871J,LJ,repair,5.5,625,0.220000
6,F-1518753o,ET,repair,5.0,289,0.294118
8,F13192545Q,UY,repair,4.3,100,0.430000
9,H12617664T,MV,refuel_check,1.0,676,0.038462
10,V-2109665o,DH,repair,4.9,196,0.350000
11,L45819441T,ND,repair,3.9,9,1.300000
12,z48466812V,OX,reparking,1.0,441,0.047619
13,e-2154304r,RT,reparking,1.0,400,0.050000
14,Q-3414660J,SZ,repair,4.6,100,0.460000
15,n-2248103n,JL,reparking,1.0,841,0.034483
16,o90119190V,ZY,reparking,1.0,729,0.037037
17,K-1010636S,KB,repair,5.2,289,0.305882
19,h-1344515n,YJ,reparking,1.0,676,0.038462
20,b-1448976u,QW,repair,6.9,1521,0.176923
21,E-1829228V,MD,repair,3.8,25,0.760000
22,m-8965256V,XS,refuel_check,2.0,400,0.100000
23,I-1538597J,RC,repair,5.8,484,0.263636
24,n28625799A,WP,refuel,1.0,676,0.038462
25,b-4266665E,MZ,reparking,1.0,289,0.058824
26,v-1209318r,QN,reparking,1.0,484,0.045455
27,h12427301o,WN,refuel,1.0,784,0.035714
28,z-7198780T,RN,repair,10.0,2304,0.208333
29,b-1441595E,SG,repair,4.5,9,1.500000
30,n31468349R,VW,reparking,1.0,576,0.041667
31,Z95207161f,UJ,repair,10.0,2304,0.208333
34,a10698807I,CS,repair,7.0,729,0.259259
35,p81056764h,VY,reparking,1.0,841,0.034483
36,K-1436228o,QH,repair,5.0,196,0.357143
37,P62164543W,HC,repair,6.8,1156,0.200000
38,c-1411220k,IJ,refuel,1.0,729,0.037037
39,B13169162p,CY,reparking,9.0,2809,0.169811
40,j51305093b,HP,reparking,1.0,784,0.035714
42,v34523863p,FN,reparking,1.0,961,0.032258
43,H97221372X,OW,refuel_check,1.0,289,0.058824
44,l17843143j,XN,repair,5.5,361,0.289474
45,j-1549044A,ZF,refuel,5.0,2209,0.106383
47,B18597537S,NR,reparking,1.0,676,0.038462
48,H29930196K,NF,repair,5.0,225,0.333333
49,p-2255017N,MN,repair,7.7,1764,0.183333
50,new_car_id,new_worker_id,refuel_check,3.5,100,0.350000

In [149]:
import pandas as pd

df = pd.read_csv('https://stepik.org/media/attachments/lesson/681964/2.2.11.csv')

# Учтите, что sort_by_list, cols2drop, columns_order_list в тестовой системе будут иметь другие значения.
sort_by_list = ['car_rating', 'riders']
cols2drop = ['random_name_1', 'target_reg', 'target_class', 'random_name_2']
columns_order_list = ['model', 'car_type', 'car_id', 'car_rating', 'year_to_start', 'year_to_work', 'riders', 'fuel_type']
critical_car_rating = 2

# В ans содержится правильный ответ. Перед отправкой своего решения, сравнитесь с ним.
ans = pd.read_csv('https://stepik.org/media/attachments/lesson/681964/2_2_11_ans.csv', index_col=0)

df.sort_values(by=sort_by_list[0], ascending=False, inplace=True)
df.sort_values(by=sort_by_list[1], inplace=True)
df.drop(df.filter(cols2drop), axis=1, inplace=True)
df = df[columns_order_list]
df.drop(df[df['car_rating'] < critical_car_rating].index, axis=0, inplace=True)
df.drop(df[(df['car_type'].isin(['economy', 'standart'])) | (df['riders'] > 10000)].index, axis=0, inplace=True)

df

,model,car_type,car_id,car_rating,year_to_start,year_to_work,riders,fuel_type
4,Mini Cooper,business,i-4390733F,4.96,2012,2018,1007,petrol
295,Mini Cooper,business,b34607341j,4.04,2011,2018,2740,petrol

In [189]:
import pandas as pd

df = pd.read_csv('https://stepik.org/media/attachments/lesson/681964/2_2_12.csv')

# В ans содержится правильный ответ. Перед отправкой своего решения, сравнитесь с ним.
ans = pd.read_csv('https://stepik.org/media/attachments/lesson/681964/2_2_12_ans.csv')

mean_rating = df['car_rating'].mean()
df['car_rating'] += 1
df['year_to_work'] += 1
df = df.loc[df['car_rating'] > mean_rating]
df['year_to_work'] = df['year_to_work'].apply(lambda x: x + 2 if x < 2017 else x // 5)
df.rename({'year_to_start': 'new_year_to_start'}, axis=1, inplace=True)
df.drop('fuel_type', axis=1, inplace=True)
df['car_type'] = df['car_type'].apply(lambda x: 'super_' + x)
result = df
result

,Unnamed: 0,car_id,model,car_type,car_rating,new_year_to_start,riders,year_to_work,target_reg,target_class
0,0,o-1588203t,VW Polo VI,super_economy,5.04,2014,61872,2018,46.175419,engine_check
1,1,B-1760099A,Renault Kaptur,super_standart,5.36,2015,95768,404,30.585652,engine_overheat
2,2,u-2045579o,Renault Kaptur,super_standart,6.94,2012,21114,404,68.091881,engine_ignition
3,3,V-4730687q,VW Tiguan,super_economy,5.10,2016,95799,403,39.808397,break_bug
4,4,K23027223e,Smart ForTwo,super_economy,4.82,2017,127971,404,37.024779,electro_bug
...,...,...,...,...,...,...,...,...,...,...
95,95,i22101695X,Fiat 500,super_business,6.16,2015,80937,404,54.714139,engine_check
96,96,a22370652k,Kia Rio,super_economy,5.56,2013,46108,404,31.320599,break_bug
97,97,H-1952766q,Tesla Model 3,super_premium,5.92,2014,58631,404,50.306346,gear_stick
98,98,r13675823Y,VW Polo VI,super_economy,5.36,2015,84108,403,34.150655,engine_fuel
99,99,I-1117298r,VW Tiguan,super_economy,5.54,2015,82807,404,111.275852,another_bug

In [228]:
import pandas as pd

df = pd.read_csv('https://stepik.org/media/attachments/lesson/681964/2_2_13.csv')

# Учтите, что cols2drop в тестовой системе будет иметь другие значения.
cols2drop = ['ride_cost', 'stop_times', 'user_ride_quality']

# В ans содержится правильный ответ. Перед отправкой своего решения, сравнитесь с ним.
ans = pd.read_csv('https://stepik.org/media/attachments/lesson/681964/2_2_13_ans.csv', index_col=0)

df['flag'] = df.apply(lambda x: 'good_line' if (x['rating'] > 5) & (x['speed_max'] < 100) else ('bad_line' if (x['rating'] > 5) & (x['speed_max'] > 100) else 'undefined'), axis=1)
df['speed_check'] = df.apply(lambda x: 'avg_more' if (x['distance'] / x['ride_duration'] > x['speed_avg']) else 'avg_less', axis=1)
df.drop(cols2drop, axis=1, inplace=True)
df.drop(df.loc[df['car_id'].isnull()].index, axis=0, inplace=True)
df

,user_id,car_id,ride_id,ride_date,rating,ride_duration,speed_avg,speed_max,distance,refueling,deviation_normal,flag,speed_check
0,Q57343968C,i-6289789v,F1u,2020-03-02,1.79,35,87,125.463335,2.930798e+03,0,-8.683,undefined,avg_less
1,N39662076X,F17991047v,J1A,2020-03-16,4.36,16,36,63.275887,4.729460e+02,0,-37.196,undefined,avg_less
2,R39462885w,l36861534V,m1v,2020-01-20,2.20,5,47,73.000000,2.836265e+02,0,3.378,undefined,avg_more
3,q32765597m,R16189354h,v1q,2020-02-24,2.82,10,31,76.838507,1.007437e+02,0,14.758,undefined,avg_less
4,n30214850g,N-1839822D,p1h,2020-01-31,3.54,17,26,53.000000,2.684519e+02,0,21.179,undefined,avg_less
5,d91252688Z,F93868144g,B1l,2020-03-11,4.19,45,41,54.815139,1.961271e+03,0,-22.288,undefined,avg_more
6,Y20252297D,S-1468454C,p1H,2020-01-28,2.99,42,67,75.324044,2.902271e+03,0,-0.000,undefined,avg_more
7,P10687833d,s-1070927u,A1x,2020-02-21,4.37,113,45,101.000000,1.389693e+03,0,-30.737,undefined,avg_less
8,u66859508D,q22813846g,r1G,2020-03-04,1.22,83,33,78.000000,2.575376e+03,0,-3.397,undefined,avg_less
9,B22048029D,W10497593m,a1L,2020-03-30,7.51,154,33,46.000000,9.417631e+02,0,-23.284,good_line,avg_less
10,E10011084Z,f-8313064a,r1F,2020-02-23,6.27,45,52,62.000000,1.275346e+03,0,0.216,good_line,avg_less
11,d72380629z,H44042475h,E1R,2020-03-24,3.83,51,54,95.000000,2.698453e+03,0,-3.397,undefined,avg_less
12,W24493253v,l93168360C,u1f,2020-03-11,3.33,31,48,66.000000,1.052461e+03,0,-2.028,undefined,avg_less
13,G14162631Z,D44517833b,M1L,2020-02-03,0.37,37,41,71.523469,1.506986e+03,0,50.284,undefined,avg_less
14,w20780850o,k49230827x,Q1c,2020-01-03,5.56,5,63,71.000000,2.504995e+02,0,4.976,good_line,avg_less
15,T17969595Q,v60921451s,e1H,2020-02-20,4.86,50,39,70.000000,1.661154e+03,0,-1.700,undefined,avg_less
16,x79241754t,G-1150322W,q1a,2020-03-29,6.48,37,47,88.544287,1.479930e+03,0,0.003,good_line,avg_less
17,X20411644t,u21483945j,i1I,2020-03-07,1.70,62,73,152.398053,4.078603e+03,0,26.047,undefined,avg_less
18,m85537990B,O19079001s,D1E,2020-03-11,5.85,3,54,64.238713,1.694870e+02,0,-13.276,good_line,avg_more
19,Q59860368x,Y-1015822T,X1L,2020-01-23,4.99,435,36,124.000000,1.086387e+03,0,-2.676,undefined,avg_less
20,D83327981K,G-1577332Q,T1t,2020-02-01,10.00,20,45,121.922976,9.388084e+02,0,-0.000,bad_line,avg_more
22,u16841707D,H12470081t,F1W,2020-01-29,3.74,21,37,63.000000,3.134473e+02,0,0.001,undefined,avg_less
23,I16576803I,V-9683916q,D1v,2020-03-29,0.73,39,88,198.388893,3.530341e+03,0,34.544,undefined,avg_more
24,J35647204F,s18801959g,x1t,2020-03-20,3.89,50,47,71.000000,2.317616e+03,0,19.251,undefined,avg_less
26,m17865791g,a10378761Y,x1Z,2020-01-03,5.31,42,39,117.000000,1.361887e+03,0,1.394,bad_line,avg_less
27,J16666485Z,R14058273F,P1g,2020-03-10,5.08,8598,52,69.000000,4.543380e+05,0,3.304,good_line,avg_more
29,N10397594A,x58256990o,C1e,2020-01-29,5.26,105,47,55.000000,1.495010e+03,0,-12.699,good_line,avg_less
30,e47183814o,C-5107111N,y1C,2020-03-13,2.13,53,51,57.000000,1.922402e+03,0,1.592,undefined,avg_less
31,U18440405R,A20603057e,k1v,2020-03-26,7.15,19499,68,167.167452,1.340785e+06,0,-5.900,bad_line,avg_more
32,V17751237h,n10206436k,z1K,2020-02-16,5.11,13,45,73.000000,2.906956e+02,0,34.149,good_line,avg_less
33,u17269130P,r-5540835r,G1P,2020-03-17,4.45,59,51,89.202101,2.560686e+03,0,20.120,undefined,avg_less
35,x11584611E,b-7314701z,W1i,2020-02-26,0.76,9535,89,172.699298,8.568368e+05,0,-1.286,undefined,avg_more
36,g19017632H,i12167734p,T1o,2020-03-08,2.33,47,54,112.000000,1.462185e+03,0,-37.663,undefined,avg_less
37,T82008116X,b-1681467p,h1Q,2020-01-09,9.01,42,31,49.000000,1.144362e+03,0,0.001,good_line,avg_less
38,u95988277B,c75592211G,q1L,2020-03-23,3.91,80,50,145.000000,2.567906e+03,0,0.002,undefined,avg_less
40,X12509304t,i-2886682y,X1r,2020-01-07,0.61,4125,51,71.000000,2.142162e+03,0,0.000,undefined,avg_less
41,F22595456y,S42953963r,E1b,2020-03-30,3.76,51,41,70.000000,2.029641e+03,0,-0.854,undefined,avg_less
42,w30463740Q,S17802902i,m1n,2020-01-05,5.12,15,54,77.388694,8.755882e+02,0,16.484,good_line,avg_more
43,b60807772D,L-1748371J,H1B,2020-01-09,4.48,28890,61,81.521292,1.800509e+06,0,2.602,undefined,avg_more
44,C22812187t,z-1435869q,S1a,2020-01-06,1.73,51,67,115.419262,3.355922e+03,0,-18.669,undefined,avg_less
46,V40970698X,x-1530392k,n1B,2020-02-03,0.10,195,42,138.000000,1.847684e+03,0,34.588,undefined,avg_less
48,s34597021Z,I21674635Q,u1X,2020-01-07,6.09,3,61,92.600171,2.318474e+02,0,1.810,good_line,avg_more
49,M11969095I,K-5008643Z,g1p,2020-03-27,6.30,6,46,74.000000,1.465846e+02,0,0.073,good_line,avg_less

In [286]:
import pandas as pd

df = pd.read_csv('https://stepik.org/media/attachments/lesson/681964/2_2_14.csv')

# В ans содержится правильный ответ. Перед отправкой своего решения, сравнитесь с ним.
ans = pd.read_csv('https://stepik.org/media/attachments/lesson/681964/2_2_14_ans.csv', index_col=0)

df['nans_num'] = df.apply(lambda x: x.isnull().sum().sum(), axis=1)
df.drop(df.loc[df['nans_num'] > 2].index, axis=0, inplace=True)
df.dropna(subset=['age'], inplace=True)
df.loc[df['user_time_accident'].isna(), ['user_time_accident']] = df['user_time_accident'].median()
df = df[['age', 'user_rides', 'user_time_accident']]
result = df

In [231]:
ans

     age  user_rides  user_time_accident
0   36.0       907.0                10.0
1   32.0       343.0                15.0
3   32.0       852.0                 5.0
4   34.0       344.0                10.0
5   35.0      1124.0                 3.0
6   34.0       677.0                 7.0
8   26.0       629.0                12.0
9   22.0       208.0                 7.0
10  22.0       157.0                 3.0
12  53.0      1412.0                10.0
13  20.0      2100.0                10.0
14  43.0         NaN                 8.0
16  42.0       864.0                14.0
18  23.0       417.0                 8.0
20  22.0       912.0                10.0
21  31.0      1234.0                 8.0
22  49.0       621.0                24.0
24  18.0       968.0                10.0
25  36.0       980.0                10.0
26  29.0       540.0                 6.0
28  36.0      1814.0                10.0
31  38.0       547.0                15.0
32  42.0       306.0                10.0
33  47.0       172.0                10.0
35  39.0      1073.0                10.0
36  18.0       805.0                15.0
37  18.0      2902.0                10.0
38  49.0         NaN                10.0
40  35.0      1206.0                 1.0
41  30.0       823.0                14.0
42  19.0      1753.0                10.0
45  47.0       996.0                10.0
47  24.0      1130.0                10.0
49  30.0       103.0                10.0